### ISSUE TITLE
set up font-family, font-size, and colors for all screens [DESCRIPTION] [ALL]

### ISSUE THREAD

**Issue by MohHajri** [DIN21SP-MobileDevProject/MDP-frontend#34]

**Comment by MohHajri** [comment]
so far we have made sure we have all screens and subscreens implemented having what we had drawn down in wireframe. This task is to polish the design, which includes using a unified **font scheme** (size, weight, family, and color), **color scheme** ( it is well-documented in Balsamiq wireframe), and **measurements** ( padding, spacing, width, and height ..etc)


this should be tackled by **all group members** 

NOTE: it is simple.

**Comment by TheZukab** [comment]
Ive pushed the custom font to use for our UI. I Implemented it to the screens (Except sample listing details) which were available to me at the time. If there are any screens pushed after that, you need to use the font provided with this push.
