### ISSUE TITLE
Set up CI for the project

### ISSUE THREAD

**Issue by Rexol** [DIN21SP-MobileDevProject/MDP-frontend#8]
- make main branch protected from direct pushes and force pushes
 - as a merge policy set up rebase and merge
 - Follow the guide to set up extra stuff (select relevant one)
 - https://proandroiddev.com/getting-started-ci-cd-for-android-project-part-3-github-actions-157857224cb1

**Comment by ni9iri** [comment]
https://github.com/n8ebel/GitHubActionsAutomationSandbox - workflow samples

**Comment by ni9iri** [comment]
Rebase merge policy 
 - 

![Image](https://user-images.githubusercontent.com/89902380/228454698-0c789669-aa3d-4c0b-bbca-fc54528d2ca8.png)


Main branch protection 
- 

![Image](https://user-images.githubusercontent.com/89902380/228454930-09b6df8a-10c2-4033-b2c5-fb6768800e1b.png)



![Image](https://user-images.githubusercontent.com/89902380/228455020-c6f7b5f6-5877-4605-813e-1a80eec3902d.png)
